//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSemana3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ClienteWSSoap")]
    public interface ClienteWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GetTokenAccesoRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenAcceso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LabSemana3.ServiceReference1.GetTokenAccesoResponse GetTokenAcceso(LabSemana3.ServiceReference1.GetTokenAccesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTokenAcceso", ReplyAction="*")]
        System.Threading.Tasks.Task<LabSemana3.ServiceReference1.GetTokenAccesoResponse> GetTokenAccesoAsync(LabSemana3.ServiceReference1.GetTokenAccesoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CabeceraSoapAcceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenAcceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string emailField;
        
        private string rolField;
        
        private System.Guid tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Guid Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenAcceso", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTokenAccesoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public LabSemana3.ServiceReference1.CabeceraSoapAcceso CabeceraSoapAcceso;
        
        public GetTokenAccesoRequest() {
        }
        
        public GetTokenAccesoRequest(LabSemana3.ServiceReference1.CabeceraSoapAcceso CabeceraSoapAcceso) {
            this.CabeceraSoapAcceso = CabeceraSoapAcceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenAccesoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTokenAccesoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public LabSemana3.ServiceReference1.TokenAcceso GetTokenAccesoResult;
        
        public GetTokenAccesoResponse() {
        }
        
        public GetTokenAccesoResponse(LabSemana3.ServiceReference1.TokenAcceso GetTokenAccesoResult) {
            this.GetTokenAccesoResult = GetTokenAccesoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteWSSoapChannel : LabSemana3.ServiceReference1.ClienteWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWSSoapClient : System.ServiceModel.ClientBase<LabSemana3.ServiceReference1.ClienteWSSoap>, LabSemana3.ServiceReference1.ClienteWSSoap {
        
        public ClienteWSSoapClient() {
        }
        
        public ClienteWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LabSemana3.ServiceReference1.GetTokenAccesoResponse LabSemana3.ServiceReference1.ClienteWSSoap.GetTokenAcceso(LabSemana3.ServiceReference1.GetTokenAccesoRequest request) {
            return base.Channel.GetTokenAcceso(request);
        }
        
        public LabSemana3.ServiceReference1.TokenAcceso GetTokenAcceso(LabSemana3.ServiceReference1.CabeceraSoapAcceso CabeceraSoapAcceso) {
            LabSemana3.ServiceReference1.GetTokenAccesoRequest inValue = new LabSemana3.ServiceReference1.GetTokenAccesoRequest();
            inValue.CabeceraSoapAcceso = CabeceraSoapAcceso;
            LabSemana3.ServiceReference1.GetTokenAccesoResponse retVal = ((LabSemana3.ServiceReference1.ClienteWSSoap)(this)).GetTokenAcceso(inValue);
            return retVal.GetTokenAccesoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LabSemana3.ServiceReference1.GetTokenAccesoResponse> LabSemana3.ServiceReference1.ClienteWSSoap.GetTokenAccesoAsync(LabSemana3.ServiceReference1.GetTokenAccesoRequest request) {
            return base.Channel.GetTokenAccesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LabSemana3.ServiceReference1.GetTokenAccesoResponse> GetTokenAccesoAsync(LabSemana3.ServiceReference1.CabeceraSoapAcceso CabeceraSoapAcceso) {
            LabSemana3.ServiceReference1.GetTokenAccesoRequest inValue = new LabSemana3.ServiceReference1.GetTokenAccesoRequest();
            inValue.CabeceraSoapAcceso = CabeceraSoapAcceso;
            return ((LabSemana3.ServiceReference1.ClienteWSSoap)(this)).GetTokenAccesoAsync(inValue);
        }
    }
}
